// 02_modelo.cypher — Red semántica integrada + jerarquía de frames (slots y facetas) + reglas + excepciones
// Generado por salida/build/gen_cypher.py desde salida/build/modelo_spec.py (no editar a mano).
// Patrón: (:Frame {tipo:'clase'}) -[:ES_UN]-> padre ; -[:ES_PARTE_DE]-> todo ; -[:TIENE_SLOT]-> (:Slot)
//         facetas como propiedades del Slot; relaciones de la red semántica entre frames con el mismo
//         verbo que usan las instancias; (:Regla)-[:USA]->(:Slot) ; (:Excepcion)-[:MODIFICA]->(:Regla)

// ---------- 1. Frames (conceptos de la red) ----------
MERGE (n:Frame {nombre: 'Cliente'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Quien formula el pedido, impone restricciones y responde aclaraciones.', n.origen = 'PI2 Matías N01 / PI2 Luciano C2', n.sinonimos = 'Solicitante, comitente', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Pedido'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Unidad de trabajo que se interpreta.', n.origen = 'PI2 Matías N02', n.sinonimos = 'Solicitud, encargo', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'ExpresionCliente'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Fragmento literal del pedido.', n.origen = 'PI2 Matías N03 (M1)', n.sinonimos = 'Frase, mención', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'ReferenciaVisual'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Imagen o boceto aportado por el cliente.', n.origen = 'PI2 Matías N04 (M2)', n.sinonimos = 'Foto de referencia, boceto', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Requerimiento'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Necesidad o condición del cliente.', n.origen = 'PI2 Matías N05', n.sinonimos = 'Requisito', n.abstracto = true, n.pendiente = '';
MERGE (n:Frame {nombre: 'RestriccionCliente'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Condición declarada como obligatoria.', n.origen = 'PI2 Matías N06 + PI2 Luciano C13', n.sinonimos = 'Restricción del cliente, exigencia', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Preferencia'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Característica deseada y negociable.', n.origen = 'PI2 Matías N07', n.sinonimos = 'Deseo', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'NecesidadFuncional'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Efecto o uso buscado sin solución técnica.', n.origen = 'PI2 Matías N08', n.sinonimos = 'Efecto buscado', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Dato'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Valor de un atributo del pedido con estado y origen.', n.origen = 'PI2 Matías N09 (M3)', n.sinonimos = 'Información del pedido', n.abstracto = true, n.pendiente = '';
MERGE (n:Frame {nombre: 'DatoConfirmado'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Dato aportado, claro y consistente.', n.origen = 'PI2 Matías N10', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'DatoFaltante'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Dato requerido que no fue aportado.', n.origen = 'PI2 Matías N11', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'DatoAmbiguo'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Dato con más de una lectura.', n.origen = 'PI2 Matías N12', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'DatoEnConflicto'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Dato incompatible con otro del mismo atributo.', n.origen = 'PI2 Matías N13', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'CategoriaDato'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Agrupación de atributos del pedido.', n.origen = 'PI2 Matías N14 (M5)', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Contradiccion'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Incompatibilidad entre dos o más datos.', n.origen = 'PI2 Matías N15 (M4)', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Aclaracion'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Pregunta al cliente para resolver un problema interpretativo.', n.origen = 'PI2 Matías N16', n.sinonimos = 'Repregunta', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'ConsultaSubmodulo'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Consulta a otro submódulo sobre la necesidad/criticidad de un dato.', n.origen = 'PI2 Matías (M10)', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'FichaRequerimientos'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Salida de Interpretación; entrada de Materiales y Manufacturabilidad.', n.origen = 'PI2 Matías N17 = PI2 Luciano C3 = PI1 Lautaro (entrada)', n.sinonimos = 'Ficha de requerimientos interpretados', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Advertencia'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Incertidumbre que viaja sin tratarse como hecho.', n.origen = 'PI2 Matías N18 (M9)', n.sinonimos = 'Reserva, observación', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Submodulo'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Agente experto del sistema.', n.origen = 'PG0 / PI2 Matías N20–N23', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'SM_Interpretacion'}) SET n.tipo = 'clase', n.submodulo = 'INT', n.descripcion = 'Interpretación técnica de requerimientos (M. Zarandon).', n.origen = 'PG0', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'SM_Materiales'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'Materiales y condiciones de instalación (L. Quiros).', n.origen = 'PG0', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'SM_Manufacturabilidad'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Manufacturabilidad y rediseño (L. Marquesini).', n.origen = 'PG0', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Cartel'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Configuración propuesta que se evalúa y, si hace falta, se rediseña.', n.origen = 'PG0 (Cartel) = PI1 Lautaro (Cartel/Configuración) = PI2 Luciano C1 (Diseño)', n.sinonimos = 'Diseño, Configuración propuesta, Modelo', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Entorno'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'Lugar donde queda el cartel y su exposición.', n.origen = 'PI1 Lautaro §2/§10 + PI2 Luciano (slot entorno) + PI2 Matías (Dato entorno)', n.sinonimos = '', n.abstracto = false, n.pendiente = '[PENDIENTE: PI2 Lautaro]';
MERGE (n:Frame {nombre: 'Material'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Insumo base del cartel.', n.origen = 'PI1 Lautaro + PI2 Luciano C6', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'PLA'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Filamento FDM, no apto intemperie.', n.origen = 'PI2 Luciano R7', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'PETG'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Filamento FDM, apto exterior.', n.origen = 'PI2 Luciano R7', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'ComponenteElectrico'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'Tiras LED, Neón LED, fuente, cableado.', n.origen = 'PI1 Lautaro §2', n.sinonimos = '', n.abstracto = false, n.pendiente = '[PENDIENTE: PI2 Lautaro]';
MERGE (n:Frame {nombre: 'Soporte'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'Superficie o estructura donde se fija el cartel.', n.origen = 'PI1 Lautaro §2', n.sinonimos = '', n.abstracto = false, n.pendiente = '[PENDIENTE: PI2 Lautaro]';
MERGE (n:Frame {nombre: 'SistemaFijacion'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Elementos que unen el cartel al soporte.', n.origen = 'PI1 Lautaro §2 + PI2 Luciano C8', n.sinonimos = 'Anclaje', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'AgenteAmbiental'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'UV, agua, temperatura, viento.', n.origen = 'PI1 Lautaro §10', n.sinonimos = '', n.abstracto = false, n.pendiente = '[PENDIENTE: PI2 Lautaro]';
MERGE (n:Frame {nombre: 'DictamenAdecuacion'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'Salida de Materiales: apto / apto con condiciones / no apto.', n.origen = 'PI1 Lautaro §2 = PI2 Luciano C4 (EvaluaciónMateriales)', n.sinonimos = '', n.abstracto = false, n.pendiente = '[PENDIENTE: PI2 Lautaro]';
MERGE (n:Frame {nombre: 'VerificacionProfesional'}) SET n.tipo = 'clase', n.submodulo = 'MAT', n.descripcion = 'Revisión estructural/eléctrica que el sistema señala y no resuelve.', n.origen = 'PI1 Lautaro §2', n.sinonimos = '', n.abstracto = false, n.pendiente = '[PENDIENTE: PI2 Lautaro]';
MERGE (n:Frame {nombre: 'Excepcion'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Condición particular que relaja o endurece una regla general.', n.origen = 'PG0 + PI1 Lautaro §6 + PI1 Luciano §6', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Regla'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Regla de producción trazable.', n.origen = 'PI1/PI2', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Geometria'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Propiedades espaciales y de trazo.', n.origen = 'PI2 Luciano C5', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Herramienta'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Impresora 3D FDM.', n.origen = 'PI2 Luciano C7', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'TecnologiaIluminacion'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Método de iluminación.', n.origen = 'PI2 Luciano C9', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'NeonFrontal'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Tira de neón en canal frontal.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Retroiluminado'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Iluminación posterior.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'RestriccionConstructiva'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Límite físico innegociable de la manufactura.', n.origen = 'PI2 Luciano C10', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'RestriccionTrazo'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Ancho mínimo para alojar la tira (6 mm).', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'RestriccionVolumen'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Cama de impresión (400 mm).', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'RestriccionPeso'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Carga admisible de la fijación.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'RestriccionTemperatura'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Deformación térmica del material.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Conflicto'}) SET n.tipo = 'clase', n.submodulo = 'COM', n.descripcion = 'Hallazgo: una característica viola un límite o criterio.', n.origen = 'PI2 Luciano C11 = PI1 Lautaro «restricción detectada»', n.sinonimos = 'Restricción detectada, problema', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'AlternativaRediseno'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Modificación propuesta para sortear un conflicto.', n.origen = 'PI2 Luciano C12', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'CambioMaterial'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = '', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'CambioGeometria'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Engrosar trazo, reducir infill.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'CambioFijacion'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Refuerzo o fijación de mayor capacidad.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'CambioTecnologia'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Pasar a retroiluminado.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'SegmentacionModular'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Dividir en piezas que entren en la cama.', n.origen = 'PI2 Luciano', n.sinonimos = '', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Recomendacion'}) SET n.tipo = 'clase', n.submodulo = 'MAN', n.descripcion = 'Salida final: confirmación o alternativas admitidas con justificación.', n.origen = 'PI2 Luciano C14', n.sinonimos = 'Ficha de rediseño', n.abstracto = false, n.pendiente = '';
MERGE (n:Frame {nombre: 'Evaluacion'}) SET n.tipo = 'clase', n.submodulo = 'TRZ', n.descripcion = 'Rastro de decisión de un caso: reglas activadas en orden.', n.origen = 'Propuesta (pregunta integrador «Trazabilidad»)', n.sinonimos = '', n.abstracto = false, n.pendiente = '';

// ---------- 2. Herencia (ES_UN) y composición (ES_PARTE_DE) ----------
MATCH (h:Frame {nombre: 'ExpresionCliente'}), (p:Frame {nombre: 'Pedido'}) MERGE (h)-[:ES_PARTE_DE]->(p);
MATCH (h:Frame {nombre: 'RestriccionCliente'}), (p:Frame {nombre: 'Requerimiento'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'Preferencia'}), (p:Frame {nombre: 'Requerimiento'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'NecesidadFuncional'}), (p:Frame {nombre: 'Requerimiento'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'DatoConfirmado'}), (p:Frame {nombre: 'Dato'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'DatoFaltante'}), (p:Frame {nombre: 'Dato'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'DatoAmbiguo'}), (p:Frame {nombre: 'Dato'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'DatoEnConflicto'}), (p:Frame {nombre: 'Dato'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'Advertencia'}), (p:Frame {nombre: 'FichaRequerimientos'}) MERGE (h)-[:ES_PARTE_DE]->(p);
MATCH (h:Frame {nombre: 'SM_Interpretacion'}), (p:Frame {nombre: 'Submodulo'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'SM_Materiales'}), (p:Frame {nombre: 'Submodulo'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'SM_Manufacturabilidad'}), (p:Frame {nombre: 'Submodulo'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'PLA'}), (p:Frame {nombre: 'Material'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'PETG'}), (p:Frame {nombre: 'Material'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'ComponenteElectrico'}), (p:Frame {nombre: 'Cartel'}) MERGE (h)-[:ES_PARTE_DE]->(p);
MATCH (h:Frame {nombre: 'Geometria'}), (p:Frame {nombre: 'Cartel'}) MERGE (h)-[:ES_PARTE_DE]->(p);
MATCH (h:Frame {nombre: 'NeonFrontal'}), (p:Frame {nombre: 'TecnologiaIluminacion'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'Retroiluminado'}), (p:Frame {nombre: 'TecnologiaIluminacion'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'RestriccionTrazo'}), (p:Frame {nombre: 'RestriccionConstructiva'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'RestriccionVolumen'}), (p:Frame {nombre: 'RestriccionConstructiva'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'RestriccionPeso'}), (p:Frame {nombre: 'RestriccionConstructiva'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'RestriccionTemperatura'}), (p:Frame {nombre: 'RestriccionConstructiva'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'CambioMaterial'}), (p:Frame {nombre: 'AlternativaRediseno'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'CambioGeometria'}), (p:Frame {nombre: 'AlternativaRediseno'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'CambioFijacion'}), (p:Frame {nombre: 'AlternativaRediseno'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'CambioTecnologia'}), (p:Frame {nombre: 'AlternativaRediseno'}) MERGE (h)-[:ES_UN]->(p);
MATCH (h:Frame {nombre: 'SegmentacionModular'}), (p:Frame {nombre: 'AlternativaRediseno'}) MERGE (h)-[:ES_UN]->(p);

// ---------- 3. Slots con facetas y demonios ----------
MERGE (s:Slot {id: 'Cliente.identificacion'}) SET s.nombre = 'identificacion', s.frame = 'Cliente', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Cliente'}), (s:Slot {id: 'Cliente.identificacion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cliente.conoce_terminologia'}) SET s.nombre = 'conoce_terminologia', s.frame = 'Cliente', s.tipo_dato = 'Enum', s.valores_permitidos = 'si | no | desconocido', s.valor_defecto = 'desconocido', s.cardinalidad = '1', s.si_necesario = 'estimar por el vocabulario de sus expresiones', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Cliente'}), (s:Slot {id: 'Cliente.conoce_terminologia'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Pedido.id'}) SET s.nombre = 'id', s.frame = 'Pedido', s.tipo_dato = 'Texto', s.valores_permitidos = 'único', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Pedido'}), (s:Slot {id: 'Pedido.id'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Pedido.estado'}) SET s.nombre = 'estado', s.frame = 'Pedido', s.tipo_dato = 'Enum', s.valores_permitidos = 'en_interpretacion | pendiente_de_aclaracion | listo_para_evaluacion', s.valor_defecto = 'en_interpretacion', s.cardinalidad = '1', s.si_necesario = 'listo solo si se cumple INT-R11; si no, pendiente si hay aclaraciones/consultas abiertas', s.si_agregado = '', s.si_modificado = '', s.nota = 'Solo INT-R11 asigna listo_para_evaluacion (M17)';
MATCH (f:Frame {nombre: 'Pedido'}), (s:Slot {id: 'Pedido.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Pedido.iteracion'}) SET s.nombre = 'iteracion', s.frame = 'Pedido', s.tipo_dato = 'Entero', s.valores_permitidos = '>= 1', s.valor_defecto = '1', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Solo la incrementa INT-R13';
MATCH (f:Frame {nombre: 'Pedido'}), (s:Slot {id: 'Pedido.iteracion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Pedido.datos_requeridos'}) SET s.nombre = 'datos_requeridos', s.frame = 'Pedido', s.tipo_dato = 'Lista(Categoría)', s.valores_permitidos = 'producto_tecnologia, dimensiones, entorno, instalacion, apariencia', s.valor_defecto = '', s.cardinalidad = '1..n', s.si_necesario = 'obtener el conjunto validado por tipo de cartel', s.si_agregado = '', s.si_modificado = '', s.nota = 'Valor provisional de PG0/PI1 [PENDIENTE: conjunto por tipo de cartel]';
MATCH (f:Frame {nombre: 'Pedido'}), (s:Slot {id: 'Pedido.datos_requeridos'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ExpresionCliente.texto_literal'}) SET s.nombre = 'texto_literal', s.frame = 'ExpresionCliente', s.tipo_dato = 'Texto', s.valores_permitidos = 'inmutable', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'No se reescribe ni se completa';
MATCH (f:Frame {nombre: 'ExpresionCliente'}), (s:Slot {id: 'ExpresionCliente.texto_literal'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ExpresionCliente.fuente'}) SET s.nombre = 'fuente', s.frame = 'ExpresionCliente', s.tipo_dato = 'Enum', s.valores_permitidos = 'mensaje | conversacion | boceto | respuesta_a_aclaracion', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ExpresionCliente'}), (s:Slot {id: 'ExpresionCliente.fuente'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ExpresionCliente.interpretaciones_posibles'}) SET s.nombre = 'interpretaciones_posibles', s.frame = 'ExpresionCliente', s.tipo_dato = 'Lista(Texto)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1..n', s.si_necesario = '', s.si_agregado = 'si hay más de una → INT-R01 (prioridad sobre INT-R07)', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ExpresionCliente'}), (s:Slot {id: 'ExpresionCliente.interpretaciones_posibles'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ReferenciaVisual.descripcion'}) SET s.nombre = 'descripcion', s.frame = 'ReferenciaVisual', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ReferenciaVisual'}), (s:Slot {id: 'ReferenciaVisual.descripcion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ReferenciaVisual.aporta_sobre'}) SET s.nombre = 'aporta_sobre', s.frame = 'ReferenciaVisual', s.tipo_dato = 'Lista(Categoría)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1..n', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'si se restringe, registrar alcance limitado (INT-R12)', s.nota = '';
MATCH (f:Frame {nombre: 'ReferenciaVisual'}), (s:Slot {id: 'ReferenciaVisual.aporta_sobre'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ReferenciaVisual.consistente_con_texto'}) SET s.nombre = 'consistente_con_texto', s.frame = 'ReferenciaVisual', s.tipo_dato = 'Enum', s.valores_permitidos = 'si | no | sin_verificar', s.valor_defecto = 'sin_verificar', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'si = no → crear Contradiccion (INT-R03)', s.nota = '';
MATCH (f:Frame {nombre: 'ReferenciaVisual'}), (s:Slot {id: 'ReferenciaVisual.consistente_con_texto'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Requerimiento.descripcion'}) SET s.nombre = 'descripcion', s.frame = 'Requerimiento', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Requerimiento'}), (s:Slot {id: 'Requerimiento.descripcion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Requerimiento.rigidez'}) SET s.nombre = 'rigidez', s.frame = 'Requerimiento', s.tipo_dato = 'Enum', s.valores_permitidos = 'obligatoria | preferencia | a_confirmar', s.valor_defecto = 'a_confirmar', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'mover a la sección de la ficha', s.nota = 'a_confirmar se trata como obligatoria en el filtro de rediseño (PI2 Luciano)';
MATCH (f:Frame {nombre: 'Requerimiento'}), (s:Slot {id: 'Requerimiento.rigidez'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Requerimiento.ambito'}) SET s.nombre = 'ambito', s.frame = 'Requerimiento', s.tipo_dato = 'Enum', s.valores_permitidos = 'plazo | recursos | dimensiones | apariencia | uso | instalacion | otro', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Requerimiento'}), (s:Slot {id: 'Requerimiento.ambito'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionCliente.rigidez'}) SET s.nombre = 'rigidez', s.frame = 'RestriccionCliente', s.tipo_dato = 'Enum', s.valores_permitidos = 'obligatoria (fijo)', s.valor_defecto = 'obligatoria', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'RestriccionCliente'}), (s:Slot {id: 'RestriccionCliente.rigidez'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionCliente.criterio'}) SET s.nombre = 'criterio', s.frame = 'RestriccionCliente', s.tipo_dato = 'Enum', s.valores_permitidos = 'fidelidad_logo | flexibilidad_estetica | tamano_final_fijo | instalacion_no_invasiva | plazo', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Slots de Luciano unificados en un criterio + nivel';
MATCH (f:Frame {nombre: 'RestriccionCliente'}), (s:Slot {id: 'RestriccionCliente.criterio'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionCliente.nivel'}) SET s.nombre = 'nivel', s.frame = 'RestriccionCliente', s.tipo_dato = 'Enum', s.valores_permitidos = 'Alta | Media | Baja', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'fidelidad_logo = Alta excluye flexibilidad = Alta';
MATCH (f:Frame {nombre: 'RestriccionCliente'}), (s:Slot {id: 'RestriccionCliente.nivel'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionCliente.evidencia'}) SET s.nombre = 'evidencia', s.frame = 'RestriccionCliente', s.tipo_dato = 'Texto', s.valores_permitidos = 'declaración explícita de obligatoriedad', s.valor_defecto = '', s.cardinalidad = '1..n', s.si_necesario = '', s.si_agregado = 'incluir en ficha.restricciones (INT-R04)', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'RestriccionCliente'}), (s:Slot {id: 'RestriccionCliente.evidencia'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Preferencia.rigidez'}) SET s.nombre = 'rigidez', s.frame = 'Preferencia', s.tipo_dato = 'Enum', s.valores_permitidos = 'preferencia (fijo)', s.valor_defecto = 'preferencia', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Solo ordena alternativas; no rechaza (Luciano)';
MATCH (f:Frame {nombre: 'Preferencia'}), (s:Slot {id: 'Preferencia.rigidez'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'NecesidadFuncional.efecto_buscado'}) SET s.nombre = 'efecto_buscado', s.frame = 'NecesidadFuncional', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'NecesidadFuncional'}), (s:Slot {id: 'NecesidadFuncional.efecto_buscado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'NecesidadFuncional.tecnologia_asociada'}) SET s.nombre = 'tecnologia_asociada', s.frame = 'NecesidadFuncional', s.tipo_dato = 'Texto', s.valores_permitidos = 'no_definida | <tecnología>', s.valor_defecto = 'no_definida', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Interpretación no puede asignarla; la propone Manufacturabilidad [PENDIENTE: criterio]';
MATCH (f:Frame {nombre: 'NecesidadFuncional'}), (s:Slot {id: 'NecesidadFuncional.tecnologia_asociada'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'NecesidadFuncional.cubre'}) SET s.nombre = 'cubre', s.frame = 'NecesidadFuncional', s.tipo_dato = 'Lista(Categoría)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..n', s.si_necesario = '', s.si_agregado = 'registrar cobertura de producto_tecnologia (INT-R07)', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'NecesidadFuncional'}), (s:Slot {id: 'NecesidadFuncional.cubre'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Dato.atributo'}) SET s.nombre = 'atributo', s.frame = 'Dato', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Dato'}), (s:Slot {id: 'Dato.atributo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Dato.categoria'}) SET s.nombre = 'categoria', s.frame = 'Dato', s.tipo_dato = 'Enum', s.valores_permitidos = 'producto_tecnologia | dimensiones | contexto_de_uso | entorno | instalacion | apariencia | restricciones', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Dato'}), (s:Slot {id: 'Dato.categoria'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Dato.valor'}) SET s.nombre = 'valor', s.frame = 'Dato', s.tipo_dato = 'Cualquiera', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = 'verificar faceta origen (INT-R09)', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Dato'}), (s:Slot {id: 'Dato.valor'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Dato.valor_normalizado'}) SET s.nombre = 'valor_normalizado', s.frame = 'Dato', s.tipo_dato = 'Número', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'mm; INT-R03 normaliza unidades';
MATCH (f:Frame {nombre: 'Dato'}), (s:Slot {id: 'Dato.valor_normalizado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Dato.origen'}) SET s.nombre = 'origen', s.frame = 'Dato', s.tipo_dato = 'Enum', s.valores_permitidos = 'cliente | respuesta_a_aclaracion', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'NO admite \'supuesto\' ni \'completado_por_sistema\' (INT-R09)';
MATCH (f:Frame {nombre: 'Dato'}), (s:Slot {id: 'Dato.origen'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Dato.estado'}) SET s.nombre = 'estado', s.frame = 'Dato', s.tipo_dato = 'Enum', s.valores_permitidos = 'confirmado | faltante | ambiguo | en_conflicto | descartado', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'reclasificar etiqueta y recalcular estado del Pedido', s.nota = '';
MATCH (f:Frame {nombre: 'Dato'}), (s:Slot {id: 'Dato.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DatoConfirmado.estado'}) SET s.nombre = 'estado', s.frame = 'DatoConfirmado', s.tipo_dato = 'Enum', s.valores_permitidos = 'confirmado (fijo)', s.valor_defecto = 'confirmado', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'DatoConfirmado'}), (s:Slot {id: 'DatoConfirmado.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DatoFaltante.criticidad'}) SET s.nombre = 'criticidad', s.frame = 'DatoFaltante', s.tipo_dato = 'Enum', s.valores_permitidos = 'bloqueante | postergable | sin_clasificar', s.valor_defecto = 'sin_clasificar', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = 'crear Aclaracion (INT-R02) y ConsultaSubmodulo si depende de otro submódulo (INT-R10)', s.si_modificado = '', s.nota = 'Criterio pendiente de adquisición; en CU1 lo resuelve R-MI-01';
MATCH (f:Frame {nombre: 'DatoFaltante'}), (s:Slot {id: 'DatoFaltante.criticidad'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DatoAmbiguo.interpretaciones'}) SET s.nombre = 'interpretaciones', s.frame = 'DatoAmbiguo', s.tipo_dato = 'Lista(Texto)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '2..n', s.si_necesario = '', s.si_agregado = 'crear Aclaracion (INT-R01)', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'DatoAmbiguo'}), (s:Slot {id: 'DatoAmbiguo.interpretaciones'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DatoEnConflicto.contradiccion'}) SET s.nombre = 'contradiccion', s.frame = 'DatoEnConflicto', s.tipo_dato = 'Ref(Contradiccion)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1..n', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'DatoEnConflicto'}), (s:Slot {id: 'DatoEnConflicto.contradiccion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'CategoriaDato.nombre'}) SET s.nombre = 'nombre', s.frame = 'CategoriaDato', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'CategoriaDato'}), (s:Slot {id: 'CategoriaDato.nombre'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Contradiccion.tipo'}) SET s.nombre = 'tipo', s.frame = 'Contradiccion', s.tipo_dato = 'Enum', s.valores_permitidos = 'texto-texto | texto-medida | texto-referencia | medida-referencia', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Contradiccion'}), (s:Slot {id: 'Contradiccion.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Contradiccion.estado'}) SET s.nombre = 'estado', s.frame = 'Contradiccion', s.tipo_dato = 'Enum', s.valores_permitidos = 'abierta | resuelta', s.valor_defecto = 'abierta', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'al resolverse: elegido → confirmado, resto → descartado', s.nota = '';
MATCH (f:Frame {nombre: 'Contradiccion'}), (s:Slot {id: 'Contradiccion.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Contradiccion.resolucion'}) SET s.nombre = 'resolucion', s.frame = 'Contradiccion', s.tipo_dato = 'Ref(Dato)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Solo la respuesta del cliente; nunca el sistema';
MATCH (f:Frame {nombre: 'Contradiccion'}), (s:Slot {id: 'Contradiccion.resolucion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Aclaracion.motivo'}) SET s.nombre = 'motivo', s.frame = 'Aclaracion', s.tipo_dato = 'Enum', s.valores_permitidos = 'ambiguedad | faltante | contradiccion | rigidez', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Aclaracion'}), (s:Slot {id: 'Aclaracion.motivo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Aclaracion.pregunta'}) SET s.nombre = 'pregunta', s.frame = 'Aclaracion', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'No debe inducir una solución técnica';
MATCH (f:Frame {nombre: 'Aclaracion'}), (s:Slot {id: 'Aclaracion.pregunta'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Aclaracion.formulacion'}) SET s.nombre = 'formulacion', s.frame = 'Aclaracion', s.tipo_dato = 'Enum', s.valores_permitidos = 'tecnica | en_terminos_de_uso', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = 'aplicar INT-R08', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Aclaracion'}), (s:Slot {id: 'Aclaracion.formulacion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Aclaracion.estado'}) SET s.nombre = 'estado', s.frame = 'Aclaracion', s.tipo_dato = 'Enum', s.valores_permitidos = 'pendiente | respondida', s.valor_defecto = 'pendiente', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'respondida → INT-R13', s.nota = '';
MATCH (f:Frame {nombre: 'Aclaracion'}), (s:Slot {id: 'Aclaracion.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ConsultaSubmodulo.pregunta'}) SET s.nombre = 'pregunta', s.frame = 'ConsultaSubmodulo', s.tipo_dato = 'Enum', s.valores_permitidos = 'es_necesario | bloqueante_o_postergable', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ConsultaSubmodulo'}), (s:Slot {id: 'ConsultaSubmodulo.pregunta'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ConsultaSubmodulo.estado'}) SET s.nombre = 'estado', s.frame = 'ConsultaSubmodulo', s.tipo_dato = 'Enum', s.valores_permitidos = 'pendiente | respondida | innecesaria', s.valor_defecto = 'pendiente', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ConsultaSubmodulo'}), (s:Slot {id: 'ConsultaSubmodulo.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ConsultaSubmodulo.respuesta'}) SET s.nombre = 'respuesta', s.frame = 'ConsultaSubmodulo', s.tipo_dato = 'Enum', s.valores_permitidos = 'bloqueante | postergable | no_necesario', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = 'actualizar dato.criticidad', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ConsultaSubmodulo'}), (s:Slot {id: 'ConsultaSubmodulo.respuesta'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'FichaRequerimientos.id'}) SET s.nombre = 'id', s.frame = 'FichaRequerimientos', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'FichaRequerimientos'}), (s:Slot {id: 'FichaRequerimientos.id'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'FichaRequerimientos.pedido'}) SET s.nombre = 'pedido', s.frame = 'FichaRequerimientos', s.tipo_dato = 'Ref(Pedido)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = 'verificar precondición pedido.estado = listo_para_evaluacion', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'FichaRequerimientos'}), (s:Slot {id: 'FichaRequerimientos.pedido'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'FichaRequerimientos.destinatarios'}) SET s.nombre = 'destinatarios', s.frame = 'FichaRequerimientos', s.tipo_dato = 'Lista(Submodulo)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1..2', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'FichaRequerimientos'}), (s:Slot {id: 'FichaRequerimientos.destinatarios'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Advertencia.motivo'}) SET s.nombre = 'motivo', s.frame = 'Advertencia', s.tipo_dato = 'Enum', s.valores_permitidos = 'dato_postergable_pendiente | rigidez_a_confirmar | alcance_limitado_de_referencia | umbral_pendiente', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Advertencia'}), (s:Slot {id: 'Advertencia.motivo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Advertencia.texto'}) SET s.nombre = 'texto', s.frame = 'Advertencia', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Advertencia'}), (s:Slot {id: 'Advertencia.texto'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Submodulo.responsable'}) SET s.nombre = 'responsable', s.frame = 'Submodulo', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Submodulo'}), (s:Slot {id: 'Submodulo.responsable'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Submodulo.tarea_experta'}) SET s.nombre = 'tarea_experta', s.frame = 'Submodulo', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Submodulo'}), (s:Slot {id: 'Submodulo.tarea_experta'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.tipo_cartel'}) SET s.nombre = 'tipo_cartel', s.frame = 'Cartel', s.tipo_dato = 'Enum', s.valores_permitidos = 'NeonLED | Corporeo | Retroiluminado', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'PG0';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.tipo_cartel'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.lleva_luz'}) SET s.nombre = 'lleva_luz', s.frame = 'Cartel', s.tipo_dato = 'Booleano', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.lleva_luz'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.tecnologia_iluminacion'}) SET s.nombre = 'tecnologia_iluminacion', s.frame = 'Cartel', s.tipo_dato = 'Enum', s.valores_permitidos = 'NeonFrontal | Retroiluminado', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = 'si vacío y lleva_luz → la propone Manufacturabilidad [PENDIENTE: criterio]; si no consta si lleva luz → devolver a Interpretación', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.tecnologia_iluminacion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.material'}) SET s.nombre = 'material', s.frame = 'Cartel', s.tipo_dato = 'Enum', s.valores_permitidos = 'PLA | PETG', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = 'entorno Exterior → MAN-R7', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.material'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.dimension_maxima_mm'}) SET s.nombre = 'dimension_maxima_mm', s.frame = 'Cartel', s.tipo_dato = 'Número', s.valores_permitidos = '> 0', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'mm (se completa desde la ficha)';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.dimension_maxima_mm'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.montaje'}) SET s.nombre = 'montaje', s.frame = 'Cartel', s.tipo_dato = 'Enum', s.valores_permitidos = 'adosado | bandera | colgado | sobre_estructura | sobre_marquesina', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'PI1 Lautaro';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.montaje'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Cartel.altura_m'}) SET s.nombre = 'altura_m', s.frame = 'Cartel', s.tipo_dato = 'Número', s.valores_permitidos = '> 0', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Cartel'}), (s:Slot {id: 'Cartel.altura_m'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Entorno.tipo'}) SET s.nombre = 'tipo', s.frame = 'Entorno', s.tipo_dato = 'Enum', s.valores_permitidos = 'interior | exterior', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Entorno'}), (s:Slot {id: 'Entorno.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Entorno.proteccion'}) SET s.nombre = 'proteccion', s.frame = 'Entorno', s.tipo_dato = 'Enum', s.valores_permitidos = 'ninguna | alero | nicho | no_informada', s.valor_defecto = 'no_informada', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Entorno'}), (s:Slot {id: 'Entorno.proteccion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Entorno.condicion_especial'}) SET s.nombre = 'condicion_especial', s.frame = 'Entorno', s.tipo_dato = 'Enum', s.valores_permitidos = 'humedad_alta | sol_directo | ninguna | no_informada', s.valor_defecto = 'no_informada', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Entorno'}), (s:Slot {id: 'Entorno.condicion_especial'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Entorno.nivel_exposicion'}) SET s.nombre = 'nivel_exposicion', s.frame = 'Entorno', s.tipo_dato = 'Enum', s.valores_permitidos = 'baja | media | alta', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = 'interpretar con R-MI-02 / R-MI-08 / R-MI-09 / R-MI-GEN', s.si_agregado = '', s.si_modificado = '', s.nota = 'Variable difusa candidata [PENDIENTE: funciones de pertenencia]';
MATCH (f:Frame {nombre: 'Entorno'}), (s:Slot {id: 'Entorno.nivel_exposicion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Material.nombre'}) SET s.nombre = 'nombre', s.frame = 'Material', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Material'}), (s:Slot {id: 'Material.nombre'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Material.apto_exterior'}) SET s.nombre = 'apto_exterior', s.frame = 'Material', s.tipo_dato = 'Booleano', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Documentado solo para PLA/PETG (propiedades térmicas FDM)';
MATCH (f:Frame {nombre: 'Material'}), (s:Slot {id: 'Material.apto_exterior'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Material.resistencia_uv'}) SET s.nombre = 'resistencia_uv', s.frame = 'Material', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '[PENDIENTE: fichas técnicas] para acrílico, PVC, ACM, chapa, silicona';
MATCH (f:Frame {nombre: 'Material'}), (s:Slot {id: 'Material.resistencia_uv'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ComponenteElectrico.tipo'}) SET s.nombre = 'tipo', s.frame = 'ComponenteElectrico', s.tipo_dato = 'Enum', s.valores_permitidos = 'tira_LED | neon_LED | fuente | cableado', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'ComponenteElectrico'}), (s:Slot {id: 'ComponenteElectrico.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ComponenteElectrico.grado_ip'}) SET s.nombre = 'grado_ip', s.frame = 'ComponenteElectrico', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'IEC 60529 [PENDIENTE: grado exigido según exposición]';
MATCH (f:Frame {nombre: 'ComponenteElectrico'}), (s:Slot {id: 'ComponenteElectrico.grado_ip'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'ComponenteElectrico.accesible'}) SET s.nombre = 'accesible', s.frame = 'ComponenteElectrico', s.tipo_dato = 'Booleano', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'R-MI-07';
MATCH (f:Frame {nombre: 'ComponenteElectrico'}), (s:Slot {id: 'ComponenteElectrico.accesible'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Soporte.tipo'}) SET s.nombre = 'tipo', s.frame = 'Soporte', s.tipo_dato = 'Enum', s.valores_permitidos = 'mamposteria | placa_de_yeso | vidrio | estructura_metalica | marquesina', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Soporte'}), (s:Slot {id: 'Soporte.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Soporte.capacidad'}) SET s.nombre = 'capacidad', s.frame = 'Soporte', s.tipo_dato = 'Enum', s.valores_permitidos = 'baja | normal', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '[PENDIENTE: peso seguro por soporte]';
MATCH (f:Frame {nombre: 'Soporte'}), (s:Slot {id: 'Soporte.capacidad'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'SistemaFijacion.tipo'}) SET s.nombre = 'tipo', s.frame = 'SistemaFijacion', s.tipo_dato = 'Enum', s.valores_permitidos = 'tarugos | anclaje_quimico | separadores | perfiles | cables | adhesivo | cinta_bifaz', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'SistemaFijacion'}), (s:Slot {id: 'SistemaFijacion.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'SistemaFijacion.requiere_perforar'}) SET s.nombre = 'requiere_perforar', s.frame = 'SistemaFijacion', s.tipo_dato = 'Booleano', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Necesario para MAN-R9';
MATCH (f:Frame {nombre: 'SistemaFijacion'}), (s:Slot {id: 'SistemaFijacion.requiere_perforar'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'SistemaFijacion.carga_admisible'}) SET s.nombre = 'carga_admisible', s.frame = 'SistemaFijacion', s.tipo_dato = 'Número', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '[PENDIENTE: valor] (RestriccionPeso)';
MATCH (f:Frame {nombre: 'SistemaFijacion'}), (s:Slot {id: 'SistemaFijacion.carga_admisible'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'AgenteAmbiental.nombre'}) SET s.nombre = 'nombre', s.frame = 'AgenteAmbiental', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'AgenteAmbiental'}), (s:Slot {id: 'AgenteAmbiental.nombre'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DictamenAdecuacion.resultado'}) SET s.nombre = 'resultado', s.frame = 'DictamenAdecuacion', s.tipo_dato = 'Enum', s.valores_permitidos = 'apto | apto_con_condiciones | no_apto | no_evaluable', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'DictamenAdecuacion'}), (s:Slot {id: 'DictamenAdecuacion.resultado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DictamenAdecuacion.condiciones'}) SET s.nombre = 'condiciones', s.frame = 'DictamenAdecuacion', s.tipo_dato = 'Lista(Texto)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..n', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'DictamenAdecuacion'}), (s:Slot {id: 'DictamenAdecuacion.condiciones'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'DictamenAdecuacion.reglas_aplicadas'}) SET s.nombre = 'reglas_aplicadas', s.frame = 'DictamenAdecuacion', s.tipo_dato = 'Lista(Regla)', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1..n', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'DictamenAdecuacion'}), (s:Slot {id: 'DictamenAdecuacion.reglas_aplicadas'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'VerificacionProfesional.tipo'}) SET s.nombre = 'tipo', s.frame = 'VerificacionProfesional', s.tipo_dato = 'Enum', s.valores_permitidos = 'estructural | electrica', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'VerificacionProfesional'}), (s:Slot {id: 'VerificacionProfesional.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Excepcion.condicion'}) SET s.nombre = 'condicion', s.frame = 'Excepcion', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Excepcion'}), (s:Slot {id: 'Excepcion.condicion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Excepcion.efecto'}) SET s.nombre = 'efecto', s.frame = 'Excepcion', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Excepcion'}), (s:Slot {id: 'Excepcion.efecto'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Regla.id'}) SET s.nombre = 'id', s.frame = 'Regla', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Regla'}), (s:Slot {id: 'Regla.id'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Regla.origen'}) SET s.nombre = 'origen', s.frame = 'Regla', s.tipo_dato = 'Enum', s.valores_permitidos = 'experto | propuesta | documental', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Regla'}), (s:Slot {id: 'Regla.origen'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Regla.estado_validacion'}) SET s.nombre = 'estado_validacion', s.frame = 'Regla', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Regla'}), (s:Slot {id: 'Regla.estado_validacion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Geometria.ancho_canal_mm'}) SET s.nombre = 'ancho_canal_mm', s.frame = 'Geometria', s.tipo_dato = 'Número', s.valores_permitidos = '> 0', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = 'recalcular Conflicto', s.nota = '';
MATCH (f:Frame {nombre: 'Geometria'}), (s:Slot {id: 'Geometria.ancho_canal_mm'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Geometria.dimension_maxima_mm'}) SET s.nombre = 'dimension_maxima_mm', s.frame = 'Geometria', s.tipo_dato = 'Número', s.valores_permitidos = '> 0', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Geometria'}), (s:Slot {id: 'Geometria.dimension_maxima_mm'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Geometria.peso_estimado_gr'}) SET s.nombre = 'peso_estimado_gr', s.frame = 'Geometria', s.tipo_dato = 'Número', s.valores_permitidos = '> 0', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Geometria'}), (s:Slot {id: 'Geometria.peso_estimado_gr'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Geometria.supera_carga_admisible'}) SET s.nombre = 'supera_carga_admisible', s.frame = 'Geometria', s.tipo_dato = 'Booleano', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Hecho del caso L-C3 mientras falte el valor límite';
MATCH (f:Frame {nombre: 'Geometria'}), (s:Slot {id: 'Geometria.supera_carga_admisible'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Herramienta.tipo'}) SET s.nombre = 'tipo', s.frame = 'Herramienta', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Herramienta'}), (s:Slot {id: 'Herramienta.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Herramienta.volumen_util_maximo'}) SET s.nombre = 'volumen_util_maximo', s.frame = 'Herramienta', s.tipo_dato = 'Número', s.valores_permitidos = '> 0', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = 'dimension_maxima_mm > volumen → Conflicto ExcedeCama (MAN-R3)', s.si_agregado = '', s.si_modificado = '', s.nota = '400 mm (documental)';
MATCH (f:Frame {nombre: 'Herramienta'}), (s:Slot {id: 'Herramienta.volumen_util_maximo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'TecnologiaIluminacion.nombre'}) SET s.nombre = 'nombre', s.frame = 'TecnologiaIluminacion', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'TecnologiaIluminacion'}), (s:Slot {id: 'TecnologiaIluminacion.nombre'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionConstructiva.tipo'}) SET s.nombre = 'tipo', s.frame = 'RestriccionConstructiva', s.tipo_dato = 'Enum', s.valores_permitidos = 'Trazo | Volumen | Peso | Temperatura', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'RestriccionConstructiva'}), (s:Slot {id: 'RestriccionConstructiva.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionConstructiva.valor_limite'}) SET s.nombre = 'valor_limite', s.frame = 'RestriccionConstructiva', s.tipo_dato = 'Número', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'Trazo 6 mm, Volumen 400 mm (documental); Peso [PENDIENTE]';
MATCH (f:Frame {nombre: 'RestriccionConstructiva'}), (s:Slot {id: 'RestriccionConstructiva.valor_limite'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'RestriccionConstructiva.unidad'}) SET s.nombre = 'unidad', s.frame = 'RestriccionConstructiva', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'RestriccionConstructiva'}), (s:Slot {id: 'RestriccionConstructiva.unidad'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Conflicto.tipo'}) SET s.nombre = 'tipo', s.frame = 'Conflicto', s.tipo_dato = 'Enum', s.valores_permitidos = 'TrazoFino | ExcedeCama | RiesgoCaida | MaterialEntorno | ComponenteEntorno | Instalacion | Mantenimiento', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Conflicto'}), (s:Slot {id: 'Conflicto.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Conflicto.origen'}) SET s.nombre = 'origen', s.frame = 'Conflicto', s.tipo_dato = 'Enum', s.valores_permitidos = 'manufactura | instalacion', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Conflicto'}), (s:Slot {id: 'Conflicto.origen'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Conflicto.estado'}) SET s.nombre = 'estado', s.frame = 'Conflicto', s.tipo_dato = 'Enum', s.valores_permitidos = 'Abierto | Resuelto | Inviable', s.valor_defecto = 'Abierto', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = 'generar alternativas (MAN-R2/R3/R4)', s.si_modificado = 'todas no viables → Inviable (MAN-R8)', s.nota = '';
MATCH (f:Frame {nombre: 'Conflicto'}), (s:Slot {id: 'Conflicto.estado'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'AlternativaRediseno.tipo_cambio'}) SET s.nombre = 'tipo_cambio', s.frame = 'AlternativaRediseno', s.tipo_dato = 'Enum', s.valores_permitidos = 'Material | Geometria | Fijacion | Tecnologia | Segmentacion', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'AlternativaRediseno'}), (s:Slot {id: 'AlternativaRediseno.tipo_cambio'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'AlternativaRediseno.impacto_estetico'}) SET s.nombre = 'impacto_estetico', s.frame = 'AlternativaRediseno', s.tipo_dato = 'Enum', s.valores_permitidos = 'Alto | Medio | Bajo', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = 'impacto Alto y fidelidad_logo Alta → viable = False', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'AlternativaRediseno'}), (s:Slot {id: 'AlternativaRediseno.impacto_estetico'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'AlternativaRediseno.viable'}) SET s.nombre = 'viable', s.frame = 'AlternativaRediseno', s.tipo_dato = 'Booleano', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '0..1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'AlternativaRediseno'}), (s:Slot {id: 'AlternativaRediseno.viable'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'AlternativaRediseno.justificacion'}) SET s.nombre = 'justificacion', s.frame = 'AlternativaRediseno', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'AlternativaRediseno'}), (s:Slot {id: 'AlternativaRediseno.justificacion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Recomendacion.tipo'}) SET s.nombre = 'tipo', s.frame = 'Recomendacion', s.tipo_dato = 'Enum', s.valores_permitidos = 'confirmacion | rediseno | inviable', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Recomendacion'}), (s:Slot {id: 'Recomendacion.tipo'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Recomendacion.justificacion'}) SET s.nombre = 'justificacion', s.frame = 'Recomendacion', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Recomendacion'}), (s:Slot {id: 'Recomendacion.justificacion'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Recomendacion.decide'}) SET s.nombre = 'decide', s.frame = 'Recomendacion', s.tipo_dato = 'Texto', s.valores_permitidos = 'fabricante (fijo)', s.valor_defecto = 'fabricante', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = 'El sistema recomienda; decide el fabricante';
MATCH (f:Frame {nombre: 'Recomendacion'}), (s:Slot {id: 'Recomendacion.decide'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Evaluacion.caso'}) SET s.nombre = 'caso', s.frame = 'Evaluacion', s.tipo_dato = 'Texto', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Evaluacion'}), (s:Slot {id: 'Evaluacion.caso'}) MERGE (f)-[:TIENE_SLOT]->(s);
MERGE (s:Slot {id: 'Evaluacion.fecha'}) SET s.nombre = 'fecha', s.frame = 'Evaluacion', s.tipo_dato = 'Fecha', s.valores_permitidos = '', s.valor_defecto = '', s.cardinalidad = '1', s.si_necesario = '', s.si_agregado = '', s.si_modificado = '', s.nota = '';
MATCH (f:Frame {nombre: 'Evaluacion'}), (s:Slot {id: 'Evaluacion.fecha'}) MERGE (f)-[:TIENE_SLOT]->(s);

// ---------- 4. Relaciones de la red semántica integrada ----------
MATCH (a:Frame {nombre: 'Cliente'}), (b:Frame {nombre: 'Pedido'}) MERGE (a)-[r:FORMULA]->(b) SET r.fuente = 'INT RL01', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Pedido'}), (b:Frame {nombre: 'ExpresionCliente'}) MERGE (a)-[r:CONTIENE]->(b) SET r.fuente = 'INT RL02', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Pedido'}), (b:Frame {nombre: 'ReferenciaVisual'}) MERGE (a)-[r:INCLUYE]->(b) SET r.fuente = 'INT RL03', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'ExpresionCliente'}), (b:Frame {nombre: 'Requerimiento'}) MERGE (a)-[r:SE_INTERPRETA_COMO]->(b) SET r.fuente = 'INT RL05', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'ExpresionCliente'}), (b:Frame {nombre: 'Dato'}) MERGE (a)-[r:APORTA]->(b) SET r.fuente = 'INT RL06', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'ReferenciaVisual'}), (b:Frame {nombre: 'Dato'}) MERGE (a)-[r:APORTA]->(b) SET r.fuente = 'INT RL07', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Requerimiento'}), (b:Frame {nombre: 'Dato'}) MERGE (a)-[r:SE_DESCRIBE_MEDIANTE]->(b) SET r.fuente = 'INT RL08', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Dato'}), (b:Frame {nombre: 'CategoriaDato'}) MERGE (a)-[r:PERTENECE_A]->(b) SET r.fuente = 'INT RL09', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Contradiccion'}), (b:Frame {nombre: 'DatoEnConflicto'}) MERGE (a)-[r:INVOLUCRA]->(b) SET r.fuente = 'INT RL10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DatoFaltante'}), (b:Frame {nombre: 'Aclaracion'}) MERGE (a)-[r:PROVOCA]->(b) SET r.fuente = 'INT RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DatoAmbiguo'}), (b:Frame {nombre: 'Aclaracion'}) MERGE (a)-[r:PROVOCA]->(b) SET r.fuente = 'INT RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Contradiccion'}), (b:Frame {nombre: 'Aclaracion'}) MERGE (a)-[r:PROVOCA]->(b) SET r.fuente = 'INT RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'SM_Interpretacion'}), (b:Frame {nombre: 'Aclaracion'}) MERGE (a)-[r:SOLICITA]->(b) SET r.fuente = 'INT RL12', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Aclaracion'}), (b:Frame {nombre: 'Cliente'}) MERGE (a)-[r:SE_DIRIGE_A]->(b) SET r.fuente = 'INT RL13', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Aclaracion'}), (b:Frame {nombre: 'Pedido'}) MERGE (a)-[r:ACTUALIZA]->(b) SET r.fuente = 'INT RL14', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'SM_Interpretacion'}), (b:Frame {nombre: 'Pedido'}) MERGE (a)-[r:EVALUA_SUFICIENCIA_DE]->(b) SET r.fuente = 'INT RL15', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DatoFaltante'}), (b:Frame {nombre: 'SM_Materiales'}) MERGE (a)-[r:REQUIERE_CONSULTA_A]->(b) SET r.fuente = 'INT RL16 (vía ConsultaSubmodulo)', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'SM_Interpretacion'}), (b:Frame {nombre: 'FichaRequerimientos'}) MERGE (a)-[r:PRODUCE]->(b) SET r.fuente = 'INT RL17', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'DatoConfirmado'}) MERGE (a)-[r:REGISTRA]->(b) SET r.fuente = 'INT RL18', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'RestriccionCliente'}) MERGE (a)-[r:PRESERVA]->(b) SET r.fuente = 'INT RL19', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'Advertencia'}) MERGE (a)-[r:INCLUYE]->(b) SET r.fuente = 'INT RL20', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'SM_Materiales'}) MERGE (a)-[r:ALIMENTA]->(b) SET r.fuente = 'INT RL21', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'SM_Manufacturabilidad'}) MERGE (a)-[r:ALIMENTA]->(b) SET r.fuente = 'INT RL21', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Pedido'}), (b:Frame {nombre: 'DatoFaltante'}) MERGE (a)-[r:OMITE]->(b) SET r.fuente = 'INT RL23', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'NecesidadFuncional'}), (b:Frame {nombre: 'CategoriaDato'}) MERGE (a)-[r:CUBRE]->(b) SET r.fuente = 'INT RL24', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'Cartel'}) MERGE (a)-[r:DESCRIBE]->(b) SET r.fuente = 'INTEG-01 (= MAN RL12 alimenta)', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'ConsultaSubmodulo'}), (b:Frame {nombre: 'SM_Materiales'}) MERGE (a)-[r:SE_DIRIGE_A]->(b) SET r.fuente = 'INT M10 / integración', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cliente'}), (b:Frame {nombre: 'RestriccionCliente'}) MERGE (a)-[r:IMPONE]->(b) SET r.fuente = 'MAN RL7', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'ConsultaSubmodulo'}), (b:Frame {nombre: 'DatoFaltante'}) MERGE (a)-[r:CONSULTA_SOBRE]->(b) SET r.fuente = 'INT M10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'Pedido'}) MERGE (a)-[r:CORRESPONDE_A]->(b) SET r.fuente = 'INT frame Ficha.pedido', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'Preferencia'}) MERGE (a)-[r:INCLUYE]->(b) SET r.fuente = 'INT frame Ficha.preferencias', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'FichaRequerimientos'}), (b:Frame {nombre: 'NecesidadFuncional'}) MERGE (a)-[r:INCLUYE]->(b) SET r.fuente = 'INT frame Ficha.necesidades_funcionales', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Advertencia'}), (b:Frame {nombre: 'ReferenciaVisual'}) MERGE (a)-[r:SOBRE]->(b) SET r.fuente = 'INT frame Advertencia.elemento', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'RestriccionCliente'}), (b:Frame {nombre: 'Cartel'}) MERGE (a)-[r:CONDICIONA]->(b) SET r.fuente = 'MAN RL8 (es_filtrada_por) / integración', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'Entorno'}) MERGE (a)-[r:SE_INSTALA_EN]->(b) SET r.fuente = 'MAT §10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'Material'}) MERGE (a)-[r:UTILIZA]->(b) SET r.fuente = 'MAT §10 usa = MAN RL2 utiliza', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'ComponenteElectrico'}) MERGE (a)-[r:UTILIZA]->(b) SET r.fuente = 'MAT §10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'SistemaFijacion'}) MERGE (a)-[r:SE_FIJA_CON]->(b) SET r.fuente = 'MAT §10 = MAN RL2', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'SistemaFijacion'}), (b:Frame {nombre: 'Soporte'}) MERGE (a)-[r:SOBRE]->(b) SET r.fuente = 'MAT §10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Material'}), (b:Frame {nombre: 'AgenteAmbiental'}) MERGE (a)-[r:RESISTE]->(b) SET r.fuente = 'MAT §10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Entorno'}), (b:Frame {nombre: 'AgenteAmbiental'}) MERGE (a)-[r:EXPONE_A]->(b) SET r.fuente = 'MAT §2 (propuesta de nombre)', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DictamenAdecuacion'}), (b:Frame {nombre: 'Cartel'}) MERGE (a)-[r:EVALUA]->(b) SET r.fuente = 'MAT §2', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DictamenAdecuacion'}), (b:Frame {nombre: 'Conflicto'}) MERGE (a)-[r:REGISTRA]->(b) SET r.fuente = 'MAT §10 presenta restricción', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DictamenAdecuacion'}), (b:Frame {nombre: 'VerificacionProfesional'}) MERGE (a)-[r:SENALA]->(b) SET r.fuente = 'MAT R-MI-06', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DictamenAdecuacion'}), (b:Frame {nombre: 'SM_Manufacturabilidad'}) MERGE (a)-[r:ALIMENTA]->(b) SET r.fuente = 'MAT §10 = MAN RL12', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'DictamenAdecuacion'}), (b:Frame {nombre: 'Advertencia'}) MERGE (a)-[r:INCLUYE]->(b) SET r.fuente = 'MAT §2 (advertencias de verificación)', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Conflicto'}), (b:Frame {nombre: 'Entorno'}) MERGE (a)-[r:CAUSADO_POR]->(b) SET r.fuente = 'MAT §10 causada_por', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Excepcion'}), (b:Frame {nombre: 'Regla'}) MERGE (a)-[r:MODIFICA]->(b) SET r.fuente = 'MAT §10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'Geometria'}) MERGE (a)-[r:TIENE]->(b) SET r.fuente = 'MAN RL1', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'TecnologiaIluminacion'}) MERGE (a)-[r:REQUIERE]->(b) SET r.fuente = 'MAN RL3', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Herramienta'}), (b:Frame {nombre: 'RestriccionConstructiva'}) MERGE (a)-[r:DEFINE]->(b) SET r.fuente = 'MAN RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'TecnologiaIluminacion'}), (b:Frame {nombre: 'RestriccionConstructiva'}) MERGE (a)-[r:DEFINE]->(b) SET r.fuente = 'MAN RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'SistemaFijacion'}), (b:Frame {nombre: 'RestriccionConstructiva'}) MERGE (a)-[r:DEFINE]->(b) SET r.fuente = 'MAN RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Material'}), (b:Frame {nombre: 'RestriccionConstructiva'}) MERGE (a)-[r:DEFINE]->(b) SET r.fuente = 'MAN RL11', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Geometria'}), (b:Frame {nombre: 'RestriccionConstructiva'}) MERGE (a)-[r:VIOLA]->(b) SET r.fuente = 'MAN RL4', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'RestriccionConstructiva'}), (b:Frame {nombre: 'Conflicto'}) MERGE (a)-[r:GENERA]->(b) SET r.fuente = 'MAN RL5', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Conflicto'}), (b:Frame {nombre: 'AlternativaRediseno'}) MERGE (a)-[r:EXIGE]->(b) SET r.fuente = 'MAN RL6', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'AlternativaRediseno'}), (b:Frame {nombre: 'AlternativaRediseno'}) MERGE (a)-[r:EXIGE]->(b) SET r.fuente = 'MAN RL6', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Conflicto'}), (b:Frame {nombre: 'Aclaracion'}) MERGE (a)-[r:PROVOCA]->(b) SET r.fuente = 'MAN R8 (vuelve a Interpretación)', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Cartel'}), (b:Frame {nombre: 'Material'}) MERGE (a)-[r:DESCARTA]->(b) SET r.fuente = 'MAN R7', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'RestriccionCliente'}), (b:Frame {nombre: 'AlternativaRediseno'}) MERGE (a)-[r:ADMITE]->(b) SET r.fuente = 'MAN RL9', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'RestriccionCliente'}), (b:Frame {nombre: 'AlternativaRediseno'}) MERGE (a)-[r:RECHAZA]->(b) SET r.fuente = 'MAN RL10', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'AlternativaRediseno'}), (b:Frame {nombre: 'Recomendacion'}) MERGE (a)-[r:CONFORMA]->(b) SET r.fuente = 'MAN RL14', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Evaluacion'}), (b:Frame {nombre: 'Pedido'}) MERGE (a)-[r:SOBRE]->(b) SET r.fuente = 'TRZ', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Evaluacion'}), (b:Frame {nombre: 'Regla'}) MERGE (a)-[r:ACTIVO]->(b) SET r.fuente = 'TRZ', r.nivel = 'esquema';
MATCH (a:Frame {nombre: 'Evaluacion'}), (b:Frame {nombre: 'Recomendacion'}) MERGE (a)-[r:CONCLUYE]->(b) SET r.fuente = 'TRZ', r.nivel = 'esquema';

// ---------- 5. Reglas trazables ----------
MERGE (n:Regla {id: 'INT-R01'}) SET n.nombre = 'Ambigüedad interpretativa', n.submodulo = 'INT', n.condicion = 'Expresión con más de una interpretación razonable y sin confirmar', n.conclusion = 'crear DatoAmbiguo (valor nulo) + Aclaración (motivo ambigüedad)', n.origen = 'propuesta', n.tipo = 'Heurística / subjetiva', n.fuente = 'PI1 Matías regla 1', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R01'}), (s:Slot {id: 'ExpresionCliente.interpretaciones_posibles'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R01'}), (s:Slot {id: 'DatoAmbiguo.interpretaciones'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R01'}), (s:Slot {id: 'Aclaracion.motivo'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R02'}) SET n.nombre = 'Dato requerido faltante', n.submodulo = 'INT', n.condicion = 'atributo de datos_requeridos sin Dato aportado ni NF que lo cubra', n.conclusion = 'crear DatoFaltante (sin_clasificar), Pedido OMITE, Aclaración', n.origen = 'propuesta', n.tipo = 'Determinística', n.fuente = 'PI1 Matías reglas 2 y 7', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R02'}), (s:Slot {id: 'Pedido.datos_requeridos'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R02'}), (s:Slot {id: 'DatoFaltante.criticidad'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R03'}) SET n.nombre = 'Contradicción entre datos', n.submodulo = 'INT', n.condicion = 'dos Datos del mismo atributo con valores incompatibles', n.conclusion = 'crear Contradicción abierta, datos en_conflicto, Aclaración', n.origen = 'propuesta', n.tipo = 'Determinística', n.fuente = 'PI1 Matías regla 3', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R03'}), (s:Slot {id: 'Contradiccion.estado'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R03'}), (s:Slot {id: 'ReferenciaVisual.consistente_con_texto'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R04'}) SET n.nombre = 'Restricción explícita', n.submodulo = 'INT', n.condicion = 'el cliente declara explícitamente que una condición debe cumplirse', n.conclusion = 'crear RestriccionCliente (obligatoria) en la ficha', n.origen = 'propuesta', n.tipo = 'Heurística / empírica', n.fuente = 'PI1 Matías regla 4', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R04'}), (s:Slot {id: 'RestriccionCliente.rigidez'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R05'}) SET n.nombre = 'Preferencia no promovible', n.submodulo = 'INT', n.condicion = 'condición expresada como deseo, sin marca de obligatoriedad', n.conclusion = 'crear Preferencia; no promover a restricción sin confirmación', n.origen = 'propuesta', n.tipo = 'Heurística / empírica', n.fuente = 'PI1 Matías regla 5', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R05'}), (s:Slot {id: 'Preferencia.rigidez'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R06'}) SET n.nombre = 'Rigidez a confirmar', n.submodulo = 'INT', n.condicion = 'no puede determinarse si es obligatoria o deseo', n.conclusion = 'rigidez = a_confirmar + Aclaración (motivo rigidez)', n.origen = 'propuesta', n.tipo = 'Subjetiva', n.fuente = 'PI1 Matías caso límite 5', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = 'no (sin caso)';
MATCH (n:Regla {id: 'INT-R06'}), (s:Slot {id: 'Requerimiento.rigidez'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R07'}) SET n.nombre = 'Necesidad funcional sin tecnología', n.submodulo = 'INT', n.condicion = 'el cliente describe un efecto y no define la tecnología (sin ambigüedad pendiente)', n.conclusion = 'crear NecesidadFuncional (tecnología no_definida) que CUBRE producto_tecnologia', n.origen = 'propuesta', n.tipo = 'Inferencial', n.fuente = 'PI1 Matías regla 6', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R07'}), (s:Slot {id: 'NecesidadFuncional.tecnologia_asociada'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R07'}), (s:Slot {id: 'NecesidadFuncional.cubre'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R08'}) SET n.nombre = 'Formulación adaptada', n.submodulo = 'INT', n.condicion = 'se crea una Aclaración', n.conclusion = 'formulación técnica si conoce_terminologia = si; si no, en términos de uso', n.origen = 'propuesta', n.tipo = 'Contextual', n.fuente = 'PI1 Matías excepción 2', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R08'}), (s:Slot {id: 'Cliente.conoce_terminologia'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R08'}), (s:Slot {id: 'Aclaracion.formulacion'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R09'}) SET n.nombre = 'Prohibición de inventar valores', n.submodulo = 'INT', n.condicion = 'se intenta asignar un valor con origen distinto de cliente / respuesta_a_aclaracion', n.conclusion = 'rechazar la asignación; el dato sigue faltante', n.origen = 'propuesta', n.tipo = 'Determinística (integridad)', n.fuente = 'PI1 Matías regla 9 + criterio de validez', n.estado_validacion = 'Validada como criterio de diseño', n.implementacion = '04 (control de integridad)';
MATCH (n:Regla {id: 'INT-R09'}), (s:Slot {id: 'Dato.origen'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R10'}) SET n.nombre = 'Consulta a otro submódulo', n.submodulo = 'INT', n.condicion = 'la necesidad o criticidad de un dato depende de materiales/instalación/manufactura', n.conclusion = 'crear ConsultaSubmodulo dirigida al submódulo dueño', n.origen = 'propuesta', n.tipo = 'Contextual', n.fuente = 'PI1 Matías regla 10', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '03 (precargada)';
MATCH (n:Regla {id: 'INT-R10'}), (s:Slot {id: 'DatoFaltante.criticidad'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R10'}), (s:Slot {id: 'ConsultaSubmodulo.pregunta'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R11'}) SET n.nombre = 'Suficiencia del pedido', n.submodulo = 'INT', n.condicion = 'todo dato requerido confirmado, cubierto por NF o faltante postergable; sin ambiguos; sin contradicciones abiertas', n.conclusion = 'Pedido.estado = listo_para_evaluacion + crear FichaRequerimientos', n.origen = 'propuesta', n.tipo = 'Determinística / inferencial', n.fuente = 'PI1 Matías regla 8', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '04';
MATCH (n:Regla {id: 'INT-R11'}), (s:Slot {id: 'Pedido.estado'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R11'}), (s:Slot {id: 'Pedido.datos_requeridos'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R11'}), (s:Slot {id: 'DatoFaltante.criticidad'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R11'}), (s:Slot {id: 'Contradiccion.estado'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R12'}) SET n.nombre = 'Herencia de incertidumbre', n.submodulo = 'INT', n.condicion = 'al crear la ficha hay faltantes postergables, rigidez a_confirmar o referencias restringidas', n.conclusion = 'crear una Advertencia por cada uno', n.origen = 'propuesta', n.tipo = 'Inferencial', n.fuente = 'PI1 Matías pregunta experta 8', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '04';
MATCH (n:Regla {id: 'INT-R12'}), (s:Slot {id: 'Advertencia.motivo'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R12'}), (s:Slot {id: 'ReferenciaVisual.aporta_sobre'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INT-R13'}) SET n.nombre = 'Reingreso de la respuesta', n.submodulo = 'INT', n.condicion = 'una Aclaración pasa a respondida', n.conclusion = 'nueva Expresión (respuesta_a_aclaracion), reevaluar R01–R03/R07, iteración + 1', n.origen = 'propuesta', n.tipo = 'Determinística', n.fuente = 'PI1 Matías flecha «Nueva info»', n.estado_validacion = 'Candidata (pendiente de validación con el experto)', n.implementacion = '04';
MATCH (n:Regla {id: 'INT-R13'}), (s:Slot {id: 'Aclaracion.estado'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INT-R13'}), (s:Slot {id: 'Pedido.iteracion'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-01'}) SET n.nombre = 'Datos mínimos', n.submodulo = 'MAT', n.condicion = 'falta entorno, tipo de soporte o dimensiones', n.conclusion = 'no evaluar; solicitar el dato a Interpretación (⇒ el faltante es bloqueante)', n.origen = 'experto', n.tipo = 'Determinística', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-01'}), (s:Slot {id: 'Entorno.tipo'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-01'}), (s:Slot {id: 'Soporte.tipo'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-01'}), (s:Slot {id: 'Cartel.dimension_maxima_mm'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-01'}), (s:Slot {id: 'ConsultaSubmodulo.respuesta'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-02'}) SET n.nombre = 'Exposición alta', n.submodulo = 'MAT', n.condicion = 'exterior, sin alero ni nicho, expuesto a sol y lluvia', n.conclusion = 'nivel_exposicion = alta', n.origen = 'experto', n.tipo = 'Difusa (hoy crisp)', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-02'}), (s:Slot {id: 'Entorno.tipo'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-02'}), (s:Slot {id: 'Entorno.proteccion'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-02'}), (s:Slot {id: 'Entorno.nivel_exposicion'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-GEN'}) SET n.nombre = 'Interior → exposición baja (regla general)', n.submodulo = 'MAT', n.condicion = 'entorno interior sin humedad alta ni sol directo', n.conclusion = 'nivel_exposicion = baja', n.origen = 'experto', n.tipo = 'Contextual', n.fuente = 'PI1 Lautaro §6 (regla general)', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-GEN'}), (s:Slot {id: 'Entorno.tipo'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-GEN'}), (s:Slot {id: 'Entorno.condicion_especial'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-GEN'}), (s:Slot {id: 'Entorno.nivel_exposicion'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-03'}) SET n.nombre = 'Componente eléctrico vs entorno', n.submodulo = 'MAT', n.condicion = 'exposición alta y componente eléctrico sin protección adecuada contra agua', n.conclusion = 'registrar conflicto componente–entorno (condición: protección IP [PENDIENTE: grado])', n.origen = 'documental+experto', n.tipo = 'Determinística', n.fuente = 'PI1 Lautaro §7 (IEC 60529)', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-03'}), (s:Slot {id: 'Entorno.nivel_exposicion'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-03'}), (s:Slot {id: 'ComponenteElectrico.grado_ip'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-04'}) SET n.nombre = 'Material vs entorno', n.submodulo = 'MAT', n.condicion = 'exposición alta y material no indicado para exterior/UV', n.conclusion = 'registrar conflicto material–entorno (condición: material apto exterior)', n.origen = 'documental+experto', n.tipo = 'Heurística', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-04'}), (s:Slot {id: 'Entorno.nivel_exposicion'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-04'}), (s:Slot {id: 'Material.apto_exterior'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-05'}) SET n.nombre = 'Soporte de baja capacidad', n.submodulo = 'MAT', n.condicion = 'soporte de baja capacidad y peso mayor al seguro', n.conclusion = 'conflicto de instalación; revisar fijación a estructura', n.origen = 'experto', n.tipo = 'Heurística', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = 'no (sin caso; umbral [PENDIENTE])';
MATCH (n:Regla {id: 'R-MI-05'}), (s:Slot {id: 'Soporte.capacidad'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-06'}) SET n.nombre = 'Verificación estructural', n.submodulo = 'MAT', n.condicion = 'gran porte, bandera o en altura con exposición al viento', n.conclusion = 'marcar verificación estructural profesional', n.origen = 'experto+documental', n.tipo = 'Contextual', n.fuente = 'PI1 Lautaro §7 (CIRSOC 102)', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04 (como advertencia: umbral [PENDIENTE])';
MATCH (n:Regla {id: 'R-MI-06'}), (s:Slot {id: 'Cartel.montaje'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-06'}), (s:Slot {id: 'Cartel.altura_m'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-07'}) SET n.nombre = 'Mantenimiento', n.submodulo = 'MAT', n.condicion = 'fuente de alimentación sin acceso', n.conclusion = 'conflicto de mantenimiento', n.origen = 'experto', n.tipo = 'Heurística', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = 'no (dato no relevado en los casos)';
MATCH (n:Regla {id: 'R-MI-07'}), (s:Slot {id: 'ComponenteElectrico.accesible'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-08'}) SET n.nombre = 'Nicho o alero', n.submodulo = 'MAT', n.condicion = 'exterior dentro de nicho o bajo alero efectivo', n.conclusion = 'reducir nivel de exposición (magnitud a validar)', n.origen = 'experto', n.tipo = 'Contextual', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = 'no (sin caso)';
MATCH (n:Regla {id: 'R-MI-08'}), (s:Slot {id: 'Entorno.proteccion'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-09'}) SET n.nombre = 'Interior exigente', n.submodulo = 'MAT', n.condicion = 'interior con humedad alta o sol directo', n.conclusion = 'evaluar con exposición media o alta', n.origen = 'experto', n.tipo = 'Contextual', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = 'no (sin caso)';
MATCH (n:Regla {id: 'R-MI-09'}), (s:Slot {id: 'Entorno.condicion_especial'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-10'}) SET n.nombre = 'Dictamen apto', n.submodulo = 'MAT', n.condicion = 'sin conflictos y datos completos', n.conclusion = 'dictamen apto; derivar a Manufacturabilidad', n.origen = 'experto', n.tipo = 'Determinística', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-10'}), (s:Slot {id: 'DictamenAdecuacion.resultado'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'R-MI-11'}) SET n.nombre = 'Dictamen apto con condiciones', n.submodulo = 'MAT', n.condicion = 'conflictos resolubles con condiciones (fijación, protección, acceso)', n.conclusion = 'dictamen apto con condiciones, listando cada condición', n.origen = 'experto', n.tipo = 'Heurística', n.fuente = 'PI1 Lautaro §7', n.estado_validacion = 'Candidata PI1, sin valores numéricos [PENDIENTE: PI2 Lautaro]', n.implementacion = '04';
MATCH (n:Regla {id: 'R-MI-11'}), (s:Slot {id: 'DictamenAdecuacion.resultado'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'R-MI-11'}), (s:Slot {id: 'DictamenAdecuacion.condiciones'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R1'}) SET n.nombre = 'Manufacturabilidad directa', n.submodulo = 'MAN', n.condicion = 'canal ≥ 6 mm, dimensión ≤ 400 mm, peso ≤ límite y sin advertencias', n.conclusion = 'confirmar manufacturabilidad (listo para laminar)', n.origen = 'documental', n.tipo = 'Determinística', n.fuente = 'PI2 Luciano R1', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R1'}), (s:Slot {id: 'Geometria.ancho_canal_mm'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R1'}), (s:Slot {id: 'Geometria.dimension_maxima_mm'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R1'}), (s:Slot {id: 'Herramienta.volumen_util_maximo'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R2'}) SET n.nombre = 'Conflicto de trazo', n.submodulo = 'MAN', n.condicion = 'ancho_canal_mm < 6 y tecnología NeónFrontal', n.conclusion = 'Conflicto TrazoFino + alternativas CambioGeometría y CambioTecnología', n.origen = 'documental', n.tipo = 'Determinística', n.fuente = 'PI2 Luciano R2 (ficha técnica neón)', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R2'}), (s:Slot {id: 'Geometria.ancho_canal_mm'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R2'}), (s:Slot {id: 'Cartel.tecnologia_iluminacion'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R2'}), (s:Slot {id: 'RestriccionConstructiva.valor_limite'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R3'}) SET n.nombre = 'Conflicto de volumen', n.submodulo = 'MAN', n.condicion = 'dimension_maxima_mm > volumen_util_maximo (400)', n.conclusion = 'Conflicto ExcedeCama + SegmentaciónModular que EXIGE CambioFijación (refuerzo)', n.origen = 'documental', n.tipo = 'Determinística', n.fuente = 'PI2 Luciano R3 (ficha impresora)', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R3'}), (s:Slot {id: 'Geometria.dimension_maxima_mm'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R3'}), (s:Slot {id: 'Herramienta.volumen_util_maximo'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R4'}) SET n.nombre = 'Peso vs fijación', n.submodulo = 'MAN', n.condicion = 'peso estimado > carga admisible de la fijación', n.conclusion = 'Conflicto RiesgoCaída + ReducirInfill y CambioFijación', n.origen = 'experto', n.tipo = 'Heurística', n.fuente = 'PI2 Luciano R4', n.estado_validacion = 'Formalizada PI2; carga admisible [PENDIENTE]', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R4'}), (s:Slot {id: 'Geometria.supera_carga_admisible'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R4'}), (s:Slot {id: 'SistemaFijacion.carga_admisible'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R5'}) SET n.nombre = 'Prioridad por flexibilidad estética', n.submodulo = 'MAN', n.condicion = 'TrazoFino y flexibilidad_estetica Alta', n.conclusion = 'seleccionar CambioGeometría, descartar CambioTecnología', n.origen = 'experto', n.tipo = 'Heurística', n.fuente = 'PI2 Luciano R5 (experiencia L. Marquesini)', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04 (sin caso que la dispare)';
MATCH (n:Regla {id: 'MAN-R5'}), (s:Slot {id: 'RestriccionCliente.criterio'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R5'}), (s:Slot {id: 'RestriccionCliente.nivel'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R6'}) SET n.nombre = 'Filtro por fidelidad al logo', n.submodulo = 'MAN', n.condicion = 'TrazoFino y fidelidad_logo Alta', n.conclusion = 'RECHAZA CambioGeometría, ADMITE CambioTecnología (retroiluminado)', n.origen = 'experto', n.tipo = 'Contextual', n.fuente = 'PI2 Luciano R6 / PI1 Luciano caso 5', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R6'}), (s:Slot {id: 'RestriccionCliente.criterio'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R6'}), (s:Slot {id: 'AlternativaRediseno.impacto_estetico'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R7'}) SET n.nombre = 'Material apto exterior', n.submodulo = 'MAN', n.condicion = 'entorno Exterior', n.conclusion = 'descartar PLA, seleccionar PETG', n.origen = 'documental', n.tipo = 'Contextual', n.fuente = 'PI2 Luciano R7 (propiedades térmicas FDM)', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R7'}), (s:Slot {id: 'Cartel.material'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R7'}), (s:Slot {id: 'Entorno.tipo'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R8'}) SET n.nombre = 'Escalado al cliente', n.submodulo = 'MAN', n.condicion = 'existe Conflicto y todas sus alternativas son no viables', n.conclusion = 'Conflicto Inviable → Aclaración (motivo rigidez) vía Interpretación', n.origen = 'propuesta', n.tipo = 'Inferencial', n.fuente = 'PI2 Luciano R8', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04 (sin caso que la dispare)';
MATCH (n:Regla {id: 'MAN-R8'}), (s:Slot {id: 'Conflicto.estado'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R8'}), (s:Slot {id: 'AlternativaRediseno.viable'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-R9'}) SET n.nombre = 'Instalación no invasiva', n.submodulo = 'MAN', n.condicion = 'RiesgoCaída e instalacion_no_invasiva', n.conclusion = 'RECHAZA CambioFijación, ADMITE ReducirInfill', n.origen = 'experto', n.tipo = 'Contextual', n.fuente = 'PI2 Luciano R9 / PI1 Luciano caso 2', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-R9'}), (s:Slot {id: 'RestriccionCliente.criterio'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-R9'}), (s:Slot {id: 'SistemaFijacion.requiere_perforar'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-FILTRO'}) SET n.nombre = 'Filtro por restricciones innegociables', n.submodulo = 'MAN', n.condicion = 'ninguna RestriccionCliente obligatoria rechaza la alternativa', n.conclusion = 'alternativa viable (ADMITE si la restricción la respeta explícitamente)', n.origen = 'experto', n.tipo = 'Determinística', n.fuente = 'PI1 Luciano etapa 5 / PI2 RL8', n.estado_validacion = 'Formalizada PI2', n.implementacion = '04';
MATCH (n:Regla {id: 'MAN-FILTRO'}), (s:Slot {id: 'RestriccionCliente.rigidez'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'MAN-FILTRO'}), (s:Slot {id: 'AlternativaRediseno.viable'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'MAN-G1'}) SET n.nombre = 'Exterior → placa base más gruesa (regla general)', n.submodulo = 'MAN', n.condicion = 'cartel exterior', n.conclusion = 'usar placa base de mayor grosor [PENDIENTE: espesor]', n.origen = 'experto', n.tipo = 'Contextual', n.fuente = 'PI1 Luciano §6 (regla general)', n.estado_validacion = 'Relevada en PI1; sin valor', n.implementacion = 'no (sin espesor relevado)';
MATCH (n:Regla {id: 'MAN-G1'}), (s:Slot {id: 'Entorno.tipo'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INTEG-01'}) SET n.nombre = 'Ficha → Cartel', n.submodulo = 'COM', n.condicion = 'existe FichaRequerimientos sin Cartel asociado', n.conclusion = 'instanciar Cartel/Entorno con los DatosConfirmados de la ficha (sin completar huecos)', n.origen = 'propuesta', n.tipo = 'Determinística', n.fuente = 'Interacción PI1 (los tres) + RL12 Luciano', n.estado_validacion = 'Propuesta de integración', n.implementacion = '04';
MATCH (n:Regla {id: 'INTEG-01'}), (s:Slot {id: 'FichaRequerimientos.id'}) MERGE (n)-[:USA]->(s);
MATCH (n:Regla {id: 'INTEG-01'}), (s:Slot {id: 'Cartel.dimension_maxima_mm'}) MERGE (n)-[:USA]->(s);
MERGE (n:Regla {id: 'INTEG-02'}) SET n.nombre = 'Recomendación y traza', n.submodulo = 'COM', n.condicion = 'Conflictos de manufactura resueltos con alternativas viables', n.conclusion = 'Recomendación que CONFORMAN las alternativas + registrar Evaluacion (reglas activadas)', n.origen = 'propuesta', n.tipo = 'Inferencial', n.fuente = 'PI1 Luciano etapa 6 + pregunta integrador «Trazabilidad»', n.estado_validacion = 'Propuesta de integración', n.implementacion = '04';
MATCH (n:Regla {id: 'INTEG-02'}), (s:Slot {id: 'Recomendacion.tipo'}) MERGE (n)-[:USA]->(s);

// ---------- 6. Excepciones ----------
MERGE (e:Excepcion {id: 'EX-01'}) SET e.condicion = 'Cartel exterior dentro de un nicho o bajo un alero efectivo', e.efecto = 'Se reduce la exposición / el grado IP exigido (magnitud a validar)', e.fuente = 'PI1 Lautaro §6';
MATCH (e:Excepcion {id: 'EX-01'}), (r:Regla {id: 'R-MI-02'}) MERGE (e)-[:MODIFICA]->(r);
MERGE (e:Excepcion {id: 'EX-02'}) SET e.condicion = 'Interior húmedo (cocina, natatorio, junto al mar) o con sol directo', e.efecto = 'Se evalúa con criterios de exterior', e.fuente = 'PI1 Lautaro §6';
MATCH (e:Excepcion {id: 'EX-02'}), (r:Regla {id: 'R-MI-GEN'}) MERGE (e)-[:MODIFICA]->(r);
MERGE (e:Excepcion {id: 'EX-03'}) SET e.condicion = 'Existe estructura portante accesible detrás del revestimiento', e.efecto = 'Pasa de no apto a apto con condiciones', e.fuente = 'PI1 Lautaro §6';
MATCH (e:Excepcion {id: 'EX-03'}), (r:Regla {id: 'R-MI-05'}) MERGE (e)-[:MODIFICA]->(r);
MERGE (e:Excepcion {id: 'EX-04'}) SET e.condicion = 'Gran porte, bandera o altura con viento', e.efecto = 'El sistema no resuelve la fijación: deriva a un profesional', e.fuente = 'PI1 Lautaro §6';
MATCH (e:Excepcion {id: 'EX-04'}), (r:Regla {id: 'R-MI-06'}) MERGE (e)-[:MODIFICA]->(r);
MERGE (e:Excepcion {id: 'EX-05'}) SET e.condicion = 'Cartel exterior dentro de un nicho', e.efecto = 'Se puede relajar el grosor de la placa base', e.fuente = 'PI1 Luciano §6';
MATCH (e:Excepcion {id: 'EX-05'}), (r:Regla {id: 'MAN-G1'}) MERGE (e)-[:MODIFICA]->(r);
MERGE (e:Excepcion {id: 'EX-06'}) SET e.condicion = 'Información ausente que puede completarse más adelante', e.efecto = 'El faltante es postergable y no bloquea (viaja como advertencia)', e.fuente = 'PI1 Matías §6';
MATCH (e:Excepcion {id: 'EX-06'}), (r:Regla {id: 'INT-R11'}) MERGE (e)-[:MODIFICA]->(r);
